### ISSUE TITLE
Heading Changes

### ISSUE THREAD

**Issue by alyssa9123** [rharbaugh/harbaughwedding#2]
Delete Story
Delete Directions
Change Wedding to Ceremony and Reception (or Ceremony/Reception or Day Of - I'm trying to decide what's better).
Add RSVP
Add Accommodations
Add Entertainment and Dining (or Entertainment/Dining)

**Comment by rharbaugh** [comment]
Can you get me a full list?
Based on what you have here and the names of the other issues I have:

Charities
Entertainment and Dining
Accomodations
Ceremony and Reception
RSVP

and based on what we talked about earlier, i'm going to add "Program".

If that's the full list can you provide an order? :)

Thanks!

**Comment by alyssa9123** [comment]
Home (if you’re creating a home page)
RSVP
Ceremony and Reception
Accommodations
Registry (name it that because if you put charities, people won’t know about it)
Entertainment and Dining
Program
Gallery (hidden until we have photos)

**Comment by rharbaugh** [comment]
Navigation is done and live
