### ISSUE TITLE
RSVP Needs

### ISSUE THREAD

**Issue by alyssa9123** [rharbaugh/harbaughwedding#3]
First Question - can you make it? 
If no, first and last name is needed.
If yes, need first and last name and add selection for if they are under 12 and if they plan on drinking for each person.
Email they can add for confirmation either way.
At bottom or top, put note that says "Email alyssamvetter@gmail.com if you have issues while trying to RSVP."

**Comment by alyssa9123** [comment]
Note to put at the bottom: RSVP submissions that do not contain someone who received an invite will be ignored.

**Comment by alyssa9123** [comment]
checkbox if address changed. if it did, add line for them to input new address

**Comment by rharbaugh** [comment]
these ones are done. there are new issues on rsvp though
