### ISSUE TITLE
Ceremony and Reception Needs

### ISSUE THREAD

**Issue by alyssa9123** [rharbaugh/harbaughwedding#4]
Make it look fancy :) 

Ceremony
Saturday, December 29th, 2018
2:00 PM
Saint Rose of Lima
215 East Front Street
Perrysburg, OH 43551

Reception
Saturday, December 29th, 2018
5:00PM Doors Open at Graystone Hall
29101 Hufford Road
Perrysburg, OH 43551

**Comment by rharbaugh** [comment]
This stuff is in contentful now.
