### ISSUE TITLE
Accommodations

### ISSUE THREAD

**Issue by alyssa9123** [rharbaugh/harbaughwedding#5]
At the top:
A block of rooms have been reserved at the Hampton Inn and Courtyard Marriott in Rossford, OH for Friday, December 28th, and Saturday, December 29th, 2018. The hotels are next door to each other. Rates and blocking dates are subject to change based on availability after the blocks are filled.

Hampton Inn
9753 Clark Drive
Rossford, OH 43460
-$89 for a king room
-$99 for a double queen room
-renovated in the last couple years
-breakfast included
-rooms must be blocked by November 22nd, 2018

Booking:
Website: http://hamptoninn.hilton.com/en/hp/groups/personalized/T/TOLPGHX-VHB-20181228/index.jhtml?WT.mc_id=POG
Phone: Call (419)662-8800, Press 0 and reference the Vetter-Harbaugh Wedding

Courtyard Marriott
9789 Clark Drive
Rossford, OH 43460
-$85 for a king room with a sleeper sofa
-$105 for a double queen room
-breakfast NOT included
-shuttle service available from reception
-rooms must be blocked by December 7th, 2018

Booking: 
Website: https://www.marriott.com/meeting-event-hotels/group-corporate-travel/groupCorp.mi?resLinkData=Vetter%20Harbaugh%20Wedding%20Room%20Block%20%5Etolcr%60VHWVHWA%7CVHWVHWB%6085.00-105.00%60USD%60false%604%6012/28/18%6012/30/18%6012/7/18&app=resvlink&stop_mobi=yes 
Phone: Call (877)757-7135 and reference the Vetter Harbaugh Wedding Room Block

**Comment by rharbaugh** [comment]
This stuff is in contentful now. Will worry about how it looks on the website later.
