### ISSUE TITLE
Entertainment and Dining

### ISSUE THREAD

**Issue by alyssa9123** [rharbaugh/harbaughwedding#6]
Earnest Brew Works
Local brewery, and XXXXXX will be on tap at the reception. The only choice of food is free popcorn, but they sometimes have food trucks. You can also bring your own food or have something delivered there (Marco’s is really close).
4342 South Detroit Avenue
Toledo, OH 43614
http://www.earnestbrewworks.com 

Hollywood Casino
1968 Miami Street
Toledo, OH 43605
http://www.hollywoodcasinotoledo.com

Toledo Museum of Art
Free admission, but you have to pay for parking. I helped with the Rebecca Louise Law exhibit where over 500,000 flowers are hanging. This exhibit costs $10/person but is well worth it! (at least in my opinion) - Alyssa
2445 Monroe Street
Toledo, OH 43620
http://www.toledomuseum.org
https://www.rebeccalouiselaw.com 

The Toledo Zoo & Aquarium
It’s the time of year for zoo lights!
2 Hippo Way
Toledo, OH 43609
https://www.toledozoo.org 

Downtown Perrysburg
Lots of shopping and restaurants. Only a block from the church.

Downtown Toledo
Lots of Bars and Restaurants. They’ve implemented DORA (Downtown Outdoor Refreshment Area) where bars in a certain area will give you a specific glass for you to carry on the way to the next bar. 
https://www.downtowntoledo.org/dora/ 

Levis Commons
Lots of shopping with some dining options.
3201 Levis Commons Boulevard
Perrysburg, OH 43551
https://www.shopleviscommons.com 

Fort Meigs
29100 West River Road
Perrysburg, OH 43551
http://www.fortmeigs.org/admission/ 

577 Foundation
577 East Front Street
Perrysburg, OH 43551
http://www.577foundation.org

Zinful
Beer and Wine Tastings
218 Louisiana Avenue
Perrysburg, OH 43551
http://www.zinfulwine.com 

Swig
One of our go-to restaurants to ride our bikes to.
219 Louisiana Avenue
Perrysburg, OH 43551
http://swigrestaurant.com

The Village Idiot
Live music 7 days a week. Pizza that is well worth the wait!
309 Conant Street
Maumee, OH 43537
https://www.villageidiotmaumee.com/pizza/ 

Dale’s Bar and Grill
Another go-to restaurant to ride our bikes to.
322 Conant Street
Maumee, OH 43537
http://www.dalesbarandgrill.com 

Perrys Burgers
Delicious, unique burgers. No beer, but they serve wine from Zinful.
220 Louisiana Avenue
Perrysburg, OH 43551

Lamplight Cafe & Bakery
Our go-to place for brunch after church.
121 West Indiana Avenue
Perrysburg, OH 43551

5th Street Pub
Great pizza and veggie meatballs that taste like they are made of meat.
105 West Fifth Street
Perrysburg, OH 43551
https://www.5thstreetpub.com

**Comment by rharbaugh** [comment]
I added all of these to contentful. I'll make separate issues for how everything looks once all the content is in.
